### ISSUE TITLE
WinDbg Not recognized

### ISSUE THREAD

**Issue by ax3l** [jazzdelightsme/WingetPathUpdater#5]
Hi,

thank you so much for this repo. I am [trying to use this on GitHub actions](https://github.com/ECP-WarpX/impactx/pull/650) to install `WinDbg` in the following way:
```yaml
    - name: Install winget
      uses: Cyberboss/install-winget@v1
    - name: Install WinDbg
      run: |
        winget install --id jazzdelightsme.WingetPathUpdater -e --accept-package-agreements --accept-source-agreements
        winget install --id Microsoft.WinDbg -e --accept-package-agreements --accept-source-agreements
    - name: Test WinDbg
      run: |
        windbg --help
```
For me, this currently shows
```
   2 |  windbg --help
     |  ~~~~~~
     | The term 'windbg' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Am I doing something wrong?
